### ISSUE TITLE
Different results for building locally and in gitlab pipeline

### ISSUE THREAD

**Issue by aranvir** [pypa/build#598]
Hi, not sure if this is the right area but I thought I try my luck here.

I'm getting different results for running `python -m build` when I'm running it locally or in the gitlab pipeline. Specifically, the build in gitlab ignores my `Manifest.in` where I'm excluding some files and directories that I don't want to have in the wheel nor in the source distribution.

I'm using the toml file below + a `setup.py` in the repo. Locally, I'm running Python 3.10.7, in gitlab I run the python:3.10-bullseye image (which has python 3.10.10). I also tested the building locally with the docker container, the result is the same as when I build it without docker.

When I build locally, I get a `.tar.gz` and a `.wheel` file. Both have the correct name and versioning. Both do not contain any content excluded in `Manifest.in`.

When I run the pipeline file below in gitlab, it also creates a `.tar.gz` and a `.wheel` file, but the the `.tar.gz` file includes the complete repository content.

Just to see what would happen, I also tried running `python setup.py sdist` and `python setup.py bdist_wheel`. But it's the exact same result both locally, and in the pipeline. So I'm all out of ideas.

I really hope someone has an idea for what the reason could be cause I already wasted lots of time on this..

**.gitlab-ci.yml**
```yaml
default:
  image: python:3.10-bullseye

  before_script:
    - python -m pip install -U pip
    - pip install -U setuptools setuptools-scm wheel build

build-dev:
  stage: build
  script:
    - cat Manifest.in  # Just to confirm the file is there and the content is correct
    - python -m build
  artifacts:
    when: on_success
    paths:
      - dist/*.whl
      - dist/*.tar.gz
```

**pyproject.toml**
```toml
[build-system]
requires = ["setuptools", "setuptools_scm[toml]"]
build-backend = "setuptools.build_meta"

[project]
name = "my-project"
requires-python = ">=3.10"
description = "My cool project"
dependencies = [
        "requests",
       # Some more dependencies here but not relevant for example
]

dynamic = ["version"]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools_scm]

```
