### ISSUE TITLE
FR: build-backend support for `poetry` within `pyproject.toml`

### ISSUE THREAD

**Issue by adam-grant-hendry** [pypa/build#644]
Related to [poetry/#2740](https://github.com/python-poetry/poetry/issues/2740) , considering [PEP 632](https://peps.python.org/pep-0632/), is it possible to use `build` as a backend with `poetry` to build platform-specific wheels and compile C-extensions?

**NOTE:** _This might not be applicable since_ `build` _is technically listed as a_ **front-end** _but I thought I'd ask since the_ `distutils` `SetuptoolsDeprecationWarning` _recommends trying_ `pypa/build` _instead_

**Comment by uranusjr** [comment]
distutils and setuptools are historically both a backend and frontend, and the deprecation suggesting build is only for the frontend part, since setuptools (absorbing distutils) only wants to be a backend moving forward, while build is only implements frontend functionalities.

So no, this does not make sense.

**Comment by adam-grant-hendry** [comment]
@uranusjr Quite alright. I was afraid this might be the case. Thank you for the clarification. I’ll go ahead and close this issue for now then.

**Comment by adam-grant-hendry** [comment]
> Hi @adam-grant-hendry, the setuptools.build_meta module implements the build APIs specified by both PEP 517 and PEP 660

Yes, I've already been doing that for some time now:

```toml
# pyproject.toml
...

[tool.poetry.build]
generate-setup-file = false
script = 'build.py'

[build-system]
requires = [
    "setuptools>=45",
    "wheel",
    "toml",
]
build-backend = "setuptools.build_meta"
```

This was first introduced in [Issue #11](https://github.com/python-poetry/poetry/issues/11#issuecomment-379484540), but is still undocumented.

I thought I was seeing the `SetuptoolsDeprecationWarning` when I ran `poetry build`, but that doesn't seem to be happening anymore.
