### ISSUE TITLE
ModuleNotFoundError: No module named 'wheel'

### ISSUE THREAD

**Issue by yungwine** [pypa/build#750]
After
```bash
 pip install wheel build
 python -m build --wheel --sdist
```
I get an error 

```bash
...
ModuleNotFoundError: No module named 'wheel'

ERROR Backend subprocess exited when trying to invoke get_requires_for_build_sdist
```

but if I downgrade `build` version to 1.0.3 the error goes away

**Comment by layday** [comment]
You're building with isolation so the wheel package from the outer environment would not be importable.  Can you share more information about the project you are trying to build?

**Comment by henryiii** [comment]
```toml
[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools"]
```

Is fine. `setuptools.build_meta` will request `wheel` if it needs it.

I’m guessing we no longer build pure setup.py packages, then?
